version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  scraping_service:
    build: .
    container_name: scraping_service
    environment:
      - MONGO_URI=mongodb://mongo:27017/scrape_db
      - JWT_SECRET=325849d9ca97f77d14c7b807e0afe54f7483a7ac17744f3a98615c970c16f2dd
      - PORT=5001
    ports:
      - "5001:5001"
    depends_on:
      - mongo

volumes:
  mongo-data:
